name: Build Unstable

on:
  push:
    tags:
      - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build Client
        run: |
          git clone --depth=1 --branch=custom-client https://github.com/mindustry-antigrief/mindustry-client-v6
          cd mindustry-client-v6
          ./gradlew desktop:dist -PclientBuild=${{ github.ref }} -PupdateUrl=${{ github.repository }}
          mv desktop/build/libs/Mindustry.jar desktop/build/libs/desktop.jar

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Mindustry/desktop/build/libs/desktop.jar
          tag: ${{ github.ref }}
